# Generated by Django 4.2.3 on 2023-07-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_realestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='img',
            field=models.CharField(default='https://www.nicepng.com/png/detail/89-898495_house-logo-png-home-address-logo-png.png', max_length=250),
        ),
    ]
